# This is a basic workflow to help you get started with Actions

name: Deploy my Lambda Function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check-out code
        uses: actions/checkout@v3
      
      - name: install python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8
          
      - name: install libraries 
        run: |
             cd  function
             python -m pip install --upgrade pip
             if [ -f requirements.txt ]; then pip install -r requiremnts.txt -t . ; fi 
            
      - name: create zip bundle
        run: |
             cd function
             zip -r ../${{ github.sha}}.zip .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: zipped-bundle
          path: ${{ github.sha}}.zip
