# This is a basic workflow that demonstrates use of  reusable workflow
# This workflows calls another reusable workflow and pass input parameters to it.

name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    uses: "./.github/workflows/called-workflow.yml"
    with:
      message: "Hello from Dibya"
