# This is a basic workflow that demonstrates use of  reusable workflow

name: Caller Workflow

on:
  workflow_dispatch:
  push:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    uses: "./.github/workflows/called-workflow.yml"
    with:
      message: "Hello from Dibya"
