# This is a basic workflow that demonstrates use of reusable workflow.
# This workflows calls another reusable workflow and pass input parameters to it.

name: Caller Workflow

on:
  workflow_dispatch:
env:
  ENV_VAR: my_env_var_msg
  
jobs:
  env_setup:
    name: Setup Dynamic Environment Variables
    runs-on: ubuntu-latest
    outputs: 
    steps:
      - name: set outputs with default values
        id: value-1
        run: echo "build-and-verify=${{ github.event.inputs.build-and-verify || 'true' }}" >> $GITHUB_OUTPUT
  
  # This workflow contains a job called "greet" which calls a reusable workflow named "called-workflow.yml"
  greet:
    uses: "./.github/workflows/called-workflow.yml"
    with:
      message: ${{ var.my_env_var }}
