# This is a basic workflow that demonstrates a reusable workflow

name: Reusable Workflow


on:
  workflow_call:
    # Inputs the workflow accepts.
    inputs:
      message:
        description: 'Messaged passed from called workflow'
        # Default value if no value is explicitly provided
        default: 'Hello World'
        # Input has to be provided for the workflow to run
        required: true
        type: string


jobs:

  display_message:
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "${{ inputs.message }}"
