# This is a basic workflow that demonstrates use of reusable workflow.
# This workflows calls another reusable workflow and pass input parameters to it.

name: Caller Workflow

on:
  workflow_dispatch:
env:
  ENV_VAR: my_env_var_msg
  
jobs:
  # This workflow contains a job called "greet" which calls a reusable workflow named "called-workflow.yml"
  greet:
    uses: "./.github/workflows/called-workflow.yml"
    with:
      message: ${{ var.my_env_var }}
